spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
restapi:
 rabbitmq:
   exchange: api.exchange
   queue: api.queue
   routingkey: api.routingkey
       
    